#!/usr/bin/bash
cwdf=$(realpath $0)
cwdd=$(dirname ${cwdf})

AT=${cwdd}
. ${AT}/constants


f_print_help () {
   f_pt 'Close Optical Drive Tool'
   printf '
   Removes power supply to the optical drive.
   Example usage -
   '${YELLOW}$0${NORMAL}'

'
}
if [ ! -f /usr/bin/sg_prevent ]
then
   echo 'sg3-utils not installed'
   exit 1
fi

me=$(whoami)
if [ ! "${me}" == 'admin_sec' ] && [ ! "${me}" == 'root' ]
then
   f_perr 'Only admin_sec can remove power supply to the optical drive.'
   exit 1
fi

if [ "$1" == '--help' ]
then
   f_print_help
   exit 0
fi
E='sudo -r sysadm_r'
if [ "${me}" == 'root' ]; then E=''; fi
CMD_RELOAD_CDDRIVE='sg_prevent --prevent=1 /dev/sr0 --verbose;modprobe -r sr_mod; sleep 2; modprobe -r cdrom;sleep 2;'
${E} bash -c "${CMD_RELOAD_CDDRIVE}"
f_pdone 'Optical drive is now powered down.'
