#!/usr/bin/bash
cwdf=$(realpath $0)
cwdd=$(dirname ${cwdf})

AT=${cwdd}
. $AT/constants

f_print_help () {
   f_pt 'Create Crypt Disk Tool'
   printf '
   Example usage -
   '${YELLOW}''$0' sdb'${NORMAL}' "Archives-A"

   Uses the strongest settings as defaults -
      - TWOFISH-XTS-ESSIV with SHA256
      - 512 key size
      - /dev/random blocking random device
      - uses PBKDF2 with argon2id
      - uses LUKS2

   We do not care about speed.

'
}


me=$(whoami)
if [ ! "$me" == 'root' ]
then
   f_perr 'Only root can create a crypt disk.'
   exit 1
fi

if [ "$1" == '--help' ]
then
   f_print_help
   exit 0
fi

O_DEV=$1
d=/dev/$O_DEV
if [ ! -b $d ] || [ "$O_DEV" == '' ]
then
   f_print_help
   f_perr 'You must specify a block device/partition path.'
   ls /dev/sd*
   echo 'Example - '$0' sdb "Archives-A"'
   exit 1
fi
O_LABEL=$2

rnd_entrop=$(cat /proc/sys/kernel/random/entropy_avail)
if [ $rnd_entrop -ge 100 ]
then
   f_pok 'This system has enough random entropy of '$rnd_entrop
else
   f_perr 'This system does not have enough random entropy for creating a secure crypt disk.'
   f_perr 'It is less than 100'
   exit 1
fi

E='sudo -r sysadm_r'
if [ "$me" == 'root' ]; then E=''; fi
which smartctl > /dev/null
if [ $? -eq 1 ]
then
   ${E} apt install smartmontools
fi
choice=''
while [ ! "$choice" == 'C' ]
do
   $E smartctl --info $d
   $E smartctl --health $d | grep "overall-health"
   $E lsblk --output "NAME,SIZE,FSTYPE,MOUNTPOINT,LABEL" $d
   $E udisksctl status | grep $O_DEV
   read -p '(C)ontinue, or (Q)uit: ' choice
   choice=$(echo $choice | tr a-z A-Z)
   if [ "$choice" == 'Q' ]; then exit 0; fi
done
$E cryptsetup --use-random --type=luks2 --key-size=512 --cipher=twofish-xts-essiv:sha256 --pbkdf=argon2id --label="$O_LABEL" luksFormat $d
if [ ! $? -eq 0 ]; then exit $?; fi
$E sync
sleep 1
f_pok 'crypt disk created'
$E cryptsetup luksOpen $d $O_DEV"_crypt"
$E sync
sleep 1
f_pok 'crypt disk mounted'
$E mkfs -t ext4 -L "$O_LABEL" /dev/mapper/$O_DEV"_crypt"
$E sync
sleep 1
f_pok 'crypt disk formatted with ext4'
$E e2fsck -fy /dev/mapper/$O_DEV"_crypt"
$E sync
sleep 1
$E cryptsetup luksClose /dev/mapper/$O_DEV"_crypt"
f_pdone 'Disk '$d' has been formatted with the strongest settings.'




