#!/usr/bin/bash
F=$1
ENARGS=''
qpdf --is-encrypted ${F}
if [ $? -eq 0 ]
then
   pass=$(zenity --title 'QPDF - Show Information' --timeout=30 --password)
   if [ "${pass}" == '' ]
   then
      notify-send -t 0 --icon=dialog-error 'QPDF - Error With Check Information' 'You must specify a password for encrypted files.'
      exit 1
   fi
   ENARGS=' --password='${pass}
fi
info=$(qpdf ${ENARGS} --check ${f})
info="${info}"'\nTotal Pages: '$(qpdf ${ENARGS} --show-npages ${f})
notify-send -t 0 --icon=dialog-information 'QPDF - Information About '${F} "${inf}o"
